<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:tns="http://exemplo.com/catalogocursos"
  targetNamespace="http://exemplo.com/catalogocursos"
  elementFormDefault="qualified">
  <xs:complexType name="Categoria">
    <xs:sequence>
      <xs:element name="id" type="xs:int" minOccurs="0" nillable="true"/>
      <xs:element name="nome" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="descricao" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Curso">
    <xs:sequence>
      <xs:element name="id" type="xs:int" minOccurs="0" nillable="true"/>
      <xs:element name="nome" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="categoria_id" type="xs:int" minOccurs="0" nillable="true"/>
      <xs:element name="categoria_nome" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="carga_horaria" type="xs:int" minOccurs="0" nillable="true"/>
      <xs:element name="preco" type="xs:decimal" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CursoArray">
    <xs:sequence>
      <xs:element name="Curso" type="tns:Curso" minOccurs="0" maxOccurs="unbounded" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CategoriaArray">
    <xs:sequence>
      <xs:element name="Categoria" type="tns:Categoria" minOccurs="0" maxOccurs="unbounded" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Administrador">
    <xs:sequence>
      <xs:element name="id" type="xs:int" minOccurs="0" nillable="true"/>
      <xs:element name="usuario" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="nome" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="criado_em" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ResultadoOperacao">
    <xs:sequence>
      <xs:element name="sucesso" type="xs:boolean" minOccurs="0" nillable="true"/>
      <xs:element name="mensagem" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="SecurityHeader">
    <xs:sequence>
      <xs:element name="token" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Token">
    <xs:sequence>
      <xs:element name="token" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="tipo" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="expira_em" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="administrador_id" type="xs:int" minOccurs="0" nillable="true"/>
      <xs:element name="administrador_nome" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ListarCursosRequest"/>
  <xs:complexType name="ListarCursosResponse">
    <xs:sequence>
      <xs:element name="listar_cursosResult" type="tns:CursoArray" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ConsultarCursoRequest">
    <xs:sequence>
      <xs:element name="curso_id" type="xs:int" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ConsultarCursoResponse">
    <xs:sequence>
      <xs:element name="consultar_cursoResult" type="tns:Curso" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="BuscarPorCategoriaRequest">
    <xs:sequence>
      <xs:element name="categoria" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="BuscarPorCategoriaResponse">
    <xs:sequence>
      <xs:element name="buscar_por_categoriaResult" type="tns:CursoArray" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ListarCategoriasRequest"/>
  <xs:complexType name="ListarCategoriasResponse">
    <xs:sequence>
      <xs:element name="listar_categoriasResult" type="tns:CategoriaArray" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ConsultarCategoriaRequest">
    <xs:sequence>
      <xs:element name="categoria_id" type="xs:int" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ConsultarCategoriaResponse">
    <xs:sequence>
      <xs:element name="consultar_categoriaResult" type="tns:Categoria" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CadastrarCategoriaRequest">
    <xs:sequence>
      <xs:element name="nome" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="descricao" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CadastrarCategoriaResponse">
    <xs:sequence>
      <xs:element name="cadastrar_categoriaResult" type="tns:Categoria" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AtualizarCategoriaRequest">
    <xs:sequence>
      <xs:element name="categoria_id" type="xs:int" minOccurs="0" nillable="true"/>
      <xs:element name="nome" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="descricao" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AtualizarCategoriaResponse">
    <xs:sequence>
      <xs:element name="atualizar_categoriaResult" type="tns:Categoria" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RemoverCategoriaRequest">
    <xs:sequence>
      <xs:element name="categoria_id" type="xs:int" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RemoverCategoriaResponse">
    <xs:sequence>
      <xs:element name="remover_categoriaResult" type="tns:ResultadoOperacao" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CadastrarCursoRequest">
    <xs:sequence>
      <xs:element name="nome" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="categoria_id" type="xs:int" minOccurs="0" nillable="true"/>
      <xs:element name="carga_horaria" type="xs:int" minOccurs="0" nillable="true"/>
      <xs:element name="preco" type="xs:decimal" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CadastrarCursoResponse">
    <xs:sequence>
      <xs:element name="cadastrar_cursoResult" type="tns:Curso" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AtualizarCursoRequest">
    <xs:sequence>
      <xs:element name="curso_id" type="xs:int" minOccurs="0" nillable="true"/>
      <xs:element name="nome" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="categoria_id" type="xs:int" minOccurs="0" nillable="true"/>
      <xs:element name="carga_horaria" type="xs:int" minOccurs="0" nillable="true"/>
      <xs:element name="preco" type="xs:decimal" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AtualizarCursoResponse">
    <xs:sequence>
      <xs:element name="atualizar_cursoResult" type="tns:Curso" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RemoverCursoRequest">
    <xs:sequence>
      <xs:element name="curso_id" type="xs:int" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RemoverCursoResponse">
    <xs:sequence>
      <xs:element name="remover_cursoResult" type="tns:ResultadoOperacao" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CriarAdministradorRequest">
    <xs:sequence>
      <xs:element name="usuario" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="senha" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="nome" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CriarAdministradorResponse">
    <xs:sequence>
      <xs:element name="criar_administradorResult" type="tns:Administrador" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="LoginRequest">
    <xs:sequence>
      <xs:element name="usuario" type="xs:string" minOccurs="0" nillable="true"/>
      <xs:element name="senha" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LoginResponse">
    <xs:sequence>
      <xs:element name="loginResult" type="tns:Token" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ValidarTokenRequest"/>
  <xs:complexType name="ValidarTokenResponse">
    <xs:sequence>
      <xs:element name="validar_tokenResult" type="xs:string" minOccurs="0" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Categoria" type="tns:Categoria"/>
  <xs:element name="Curso" type="tns:Curso"/>
  <xs:element name="CursoArray" type="tns:CursoArray"/>
  <xs:element name="CategoriaArray" type="tns:CategoriaArray"/>
  <xs:element name="Administrador" type="tns:Administrador"/>
  <xs:element name="ResultadoOperacao" type="tns:ResultadoOperacao"/>
  <xs:element name="SecurityHeader" type="tns:SecurityHeader"/>
  <xs:element name="Token" type="tns:Token"/>

  <xs:element name="listar_cursos" type="tns:ListarCursosRequest"/>
  <xs:element name="listar_cursosResponse" type="tns:ListarCursosResponse"/>
  <xs:element name="consultar_curso" type="tns:ConsultarCursoRequest"/>
  <xs:element name="consultar_cursoResponse" type="tns:ConsultarCursoResponse"/>
  <xs:element name="buscar_por_categoria" type="tns:BuscarPorCategoriaRequest"/>
  <xs:element name="buscar_por_categoriaResponse" type="tns:BuscarPorCategoriaResponse"/>
  <xs:element name="listar_categorias" type="tns:ListarCategoriasRequest"/>
  <xs:element name="listar_categoriasResponse" type="tns:ListarCategoriasResponse"/>
  <xs:element name="consultar_categoria" type="tns:ConsultarCategoriaRequest"/>
  <xs:element name="consultar_categoriaResponse" type="tns:ConsultarCategoriaResponse"/>
  <xs:element name="cadastrar_categoria" type="tns:CadastrarCategoriaRequest"/>
  <xs:element name="cadastrar_categoriaResponse" type="tns:CadastrarCategoriaResponse"/>
  <xs:element name="atualizar_categoria" type="tns:AtualizarCategoriaRequest"/>
  <xs:element name="atualizar_categoriaResponse" type="tns:AtualizarCategoriaResponse"/>
  <xs:element name="remover_categoria" type="tns:RemoverCategoriaRequest"/>
  <xs:element name="remover_categoriaResponse" type="tns:RemoverCategoriaResponse"/>
  <xs:element name="cadastrar_curso" type="tns:CadastrarCursoRequest"/>
  <xs:element name="cadastrar_cursoResponse" type="tns:CadastrarCursoResponse"/>
  <xs:element name="atualizar_curso" type="tns:AtualizarCursoRequest"/>
  <xs:element name="atualizar_cursoResponse" type="tns:AtualizarCursoResponse"/>
  <xs:element name="remover_curso" type="tns:RemoverCursoRequest"/>
  <xs:element name="remover_cursoResponse" type="tns:RemoverCursoResponse"/>
  <xs:element name="criar_administrador" type="tns:CriarAdministradorRequest"/>
  <xs:element name="criar_administradorResponse" type="tns:CriarAdministradorResponse"/>
  <xs:element name="login" type="tns:LoginRequest"/>
  <xs:element name="loginResponse" type="tns:LoginResponse"/>
  <xs:element name="validar_token" type="tns:ValidarTokenRequest"/>
  <xs:element name="validar_tokenResponse" type="tns:ValidarTokenResponse"/>
</xs:schema>
